name: Deploy Flask App to Google Cloud Run

on:
  push:
    branches:
      - main  # Nebo jiná větev, podle potřeby

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-central4  # Zvol si region
  SERVICE_NAME: naocicd  # Název služby
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/naocicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repozitáře
      - name: Checkout code
        uses: actions/checkout@v2

      # Nastavení Google Cloud autentizace
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Nastavení Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # Sestavení a pushnutí Docker image
      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Deploy na Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_NAME \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --port 8080
