name: Deploy Flask App to Google Cloud Run

on:
  push:
    branches:
      - main  # Spustí se při pushnutí do hlavní větve

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west4  # ✅ Nastavený region
  SERVICE_NAME: flask-app  # Název Cloud Run služby
  REPO_NAME: cicd  # Název Artifact Registry repozitáře
  IMAGE_NAME: europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cicd/flask-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker authentication
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_NAME \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --timeout=300s
