name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Spustí CI/CD na každém pushi do hlavní větve
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Docker build and push
        run: |
          # Přihlásíme se do Google Cloud a nastavíme autentifikaci
          echo ${{ secrets.GCP_SA_KEY }} | gcloud auth activate-service-account --key-file=-
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

          # Nastavíme proměnnou pro název Docker obrazu
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-flask-app:latest

          # Vytvoříme Docker obraz a nahrajeme na Container Registry
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          # Nasazení aplikace na Google Cloud Run
          gcloud run deploy my-flask-app \
            --image $IMAGE_NAME \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
